spring:
  application:
    name: padel-draft-api
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/padel_draft}
    username: ${DATABASE_USERNAME:padel}
    password: ${DATABASE_PASSWORD:padel}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
